version: '3.8'

services:
  flask-app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
